package org.example.email;

import jakarta.mail.*;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;

import java.time.Instant;
import java.util.Properties;

public class EmailSender {

    private final String smtpHost;
    private final int smtpPort;
    private final String smtpUser;
    private final String smtpPass;
    private final String fromEmail;
    private final Session session;

    public EmailSender() {
        this.smtpHost = System.getenv().getOrDefault("SMTP_HOST", "smtp.gmail.com");
        this.smtpPort = Integer.parseInt(System.getenv().getOrDefault("SMTP_PORT", "587"));
        this.smtpUser = System.getenv().getOrDefault("SMTP_USER", "");
        this.smtpPass = System.getenv().getOrDefault("SMTP_PASS", "");
        this.fromEmail = System.getenv().getOrDefault("FROM_EMAIL", "alerts@canary.local");

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", smtpHost);
        props.put("mail.smtp.port", String.valueOf(smtpPort));

        this.session = Session.getInstance(props, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(smtpUser, smtpPass);
            }
        });
    }

    public boolean sendRedirectAlert(String toEmail, String token, String destinationUrl,
                                     String ip, String ipVersion, String userAgent,
                                     Instant time) {
        if (smtpUser.isBlank() || smtpPass.isBlank()) {
            System.err.println("[WARN] SMTP credentials not set, skipping email");
            return false;
        }

        String subject = "Tracking link opened";
        String body = String.format(
                "Your tracking link was opened.\n\n" +
                "Link token: %s\n" +
                "Destination: %s\n" +
                "Time: %s\n" +
                "IP: %s (%s)\n" +
                "User-Agent: %s\n\n" +
                "This event was generated by a link you created.\n" +
                "No exact physical location is recorded — only approximate geolocation data from the IP address.",
                token, destinationUrl, time, ip, ipVersion, userAgent
        );

        return sendEmail(toEmail, subject, body);
    }

    private boolean sendEmail(String toEmail, String subject, String body) {
        try {
            Message msg = new MimeMessage(session);
            msg.setFrom(new InternetAddress(fromEmail));
            msg.setRecipient(Message.RecipientType.TO, new InternetAddress(toEmail));
            msg.setSubject(subject);
            msg.setText(body);
            Transport.send(msg);
            System.out.println("[EMAIL] Alert sent to " + toEmail);
            return true;
        } catch (MessagingException e) {
            System.err.println("[EMAIL ERROR] " + e.getMessage());
            return false;
        }
    }
}
