package org.example.tracking;

import jakarta.mail.*;
import jakarta.mail.internet.InternetAddress;
import jakarta.mail.internet.MimeMessage;
import org.example.db.Database.TokenRecord;
import org.example.db.Database.EventRecord;

import java.time.Instant;
import java.util.Properties;

public class EmailSender {

    private static Session session;
    private static String fromEmail;
    private static boolean initialized = false;

    public static void init(String host, int port, String user, String pass) {
        fromEmail = System.getenv().getOrDefault("FROM_EMAIL", user);

        // ponytail: don't fail startup if SMTP is not configured — emails just won't send
        if (user == null || user.isBlank()) {
            System.out.println("[EMAIL] SMTP_USER not set — email alerts disabled");
            return;
        }
        if (pass == null || pass.isBlank()) {
            System.out.println("[EMAIL] SMTP_PASS not set — email alerts disabled");
            return;
        }

        Properties props = new Properties();
        props.put("mail.smtp.auth", "true");
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host", host);
        props.put("mail.smtp.port", String.valueOf(port));

        session = Session.getInstance(props, new Authenticator() {
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(user, pass);
            }
        });

        initialized = true;
        System.out.println("[EMAIL] SMTP configured: " + host + ":" + port + " (user: " + user + ")");
    }

    public static void sendAlert(TokenRecord token, EventRecord event) {
        if (!initialized) {
            System.err.println("[EMAIL] Alert not sent — SMTP not configured");
            return;
        }

        String subject = "IP Tracker: Link opened";
        String body = formatEmail(token, event);

        try {
            Message msg = new MimeMessage(session);
            msg.setFrom(new InternetAddress(fromEmail));
            msg.setRecipient(Message.RecipientType.TO,
                    new InternetAddress(token.notificationEmail()));
            msg.setSubject(subject);
            msg.setText(body);
            Transport.send(msg);
            System.out.println("[EMAIL] Alert sent to " + token.notificationEmail() + " for token " + token.token());
        } catch (MessagingException e) {
            // Don't prevent the redirect/event storage — just log
            System.err.println("[EMAIL ERROR] Failed to send alert: " + e.getMessage());
        }
    }

    private static String formatEmail(TokenRecord token, EventRecord event) {
        return "Your tracking link was opened:\n\n" +
                "Token:        " + event.tokenId() + "\n" +
                "Timestamp:    " + event.timestamp() + "\n" +
                "IP address:   " + event.ip() + "\n" +
                "IP version:   " + event.ipVersion() + "\n" +
                "Country:      " + (event.country() != null ? event.country() : "n/a") + "\n" +
                "Region:       " + (event.region() != null ? event.region() : "n/a") + "\n" +
                "City:         " + (event.city() != null ? event.city() : "n/a") + "\n" +
                "Coordinates:  " + (event.latitude() != null && event.longitude() != null
                    ? event.latitude() + ", " + event.longitude() : "n/a") + "\n" +
                "Timezone:     " + (event.timezone() != null ? event.timezone() : "n/a") + "\n" +
                "ASN:          " + (event.asn() != null ? event.asn() : "n/a") + "\n" +
                "Organization: " + (event.organization() != null ? event.organization() : "n/a") + "\n" +
                "ISP:          " + (event.isp() != null ? event.isp() : "n/a") + "\n" +
                "Privacy:      " + (event.privacy() != null ? event.privacy() : "n/a") + "\n" +
                "User-Agent:   " + (event.userAgent() != null ? event.userAgent() : "n/a") + "\n" +
                "Referer:      " + (event.referer() != null ? event.referer() : "n/a") + "\n" +
                "Destination:  " + token.destinationUrl() + "\n\n" +
                "Note: The location data is IP-based and approximate — it does not provide exact GPS coordinates or street-level location.\n" +
                "\nThis event was generated by a tracking link you created. No other data was collected.";
    }
}
